#!/usr/bin/env dash

# ------------------------------------------------------------
# General Settings
# ------------------------------------------------------------

bspc config split_ratio             0.50
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config pointer_follows_focus   true

# ------------------------------------------------------------
# Window settings
# ------------------------------------------------------------

# window borders / fill
bspc config borderless_monocle      false
bspc config border_width            2
bspc config focused_border_color    "#0d497b"
bspc config normal_border_color     "#333333"
bspc config presel_feedback_color   "#0d497b"

# gap / padding
gap_size=0
bspc config gapless_monocle         true
bspc config window_gap              $gap_size
bspc config top_padding             $PANEL_HEIGHT
bspc config bottom_padding          $gap_size
bspc config left_padding            $gap_size
bspc config right_padding           $gap_size
bspc config external_rules_command  ~/.config/bspwm/external_rules

# ------------------------------------------------------------
# Workspaces
# ------------------------------------------------------------
bspc monitor -d 1term 2web 3files 4mus 5torr 6misc 7mail 8news

# ------------------------------------------------------------
# Rules
# ------------------------------------------------------------

bspc rule -a chromium desktop=^2 focus=on follow=true
bspc rule -a Gcolor2 state=tiled
bspc rule -a newsbeuter desktop=^8
bspc rule -a mutt desktop=^7
bspc rule -a *:ranger desktop=^3
bspc rule -a rtorrent desktop=^5
bspc rule -a *:cal state=floating # +external_rules
#bspc rule -a *:tmux state=fullscreen

# ------------------------------------------------------------
# Autostart
# ------------------------------------------------------------

xsetroot -cursor_name left_ptr
~/.config/bspwm/panel &
