#!/usr/bin/env dash

# ------------------------------------------------------------
# General Settings
# ------------------------------------------------------------

bspc config external_rules_command  ~/.config/bspwm/external_rules
bspc config split_ratio             0.50
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config click_to_focus          true

# ignore EWMH focus requests coming from applications
bspc config ignore_ewmh_focus       true

# window borders / fill
bspc config borderless_monocle      false
bspc config border_width            2
#bspc config focused_border_color    "#0d497b"
bspc config focused_border_color    "#285577"
bspc config normal_border_color     "#333333"
#bspc config presel_feedback_color   "#0d497b"
bspc config presel_feedback_color   "#285577"

# gap / padding
bspc config gapless_monocle         true
bspc config window_gap              0
bspc config top_padding             20
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

# remove disabled/unplugged monitors and move their
# desktops to the first monitor (laptop display)
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# mouse / pointer binding (not handled by sxhkd anymore)
# mod1 = alt key
# mod4 = super (windows) key
bspc config pointer_modifier        mod4

# ------------------------------------------------------------
# Desktops
# ------------------------------------------------------------

bspc monitor -d term web files mail torr desk deskb deskc

# ------------------------------------------------------------
# Rules
# ------------------------------------------------------------

bspc rule -a luakit desktop=^2
bspc rule -a *:ÁNYK desktop=^6
bspc rule -a *:chromium desktop=^2
bspc rule -a *:calibre desktop=^6
bspc rule -a Firefox desktop=^2
bspc rule -a Gcolor2 state=tiled split_ratio=0.6
bspc rule -a *:zathura state=tiled
bspc rule -a *:VirtualBox desktop=^6
bspc rule -a *:soffice desktop=^6
bspc rule -a Geary desktop=^4
bspc rule -a Gimp desktop=^6
bspc rule -a Inkscape desktop=^6
bspc rule -a Gtkpod desktop=^6
bspc rule -a *:szamlazo.exe desktop=^6
bspc rule -a *:dosbox desktop=^6 state=floating
bspc rule -a *:scummvm.exe desktop=^6
bspc rule -a *:sdlmame desktop=^6 state=floating
bspc rule -a *:zsnes desktop=^6 state=floating
bspc rule -a *:fceux desktop=^6 state=floating
bspc rule -a *:hiro desktop=^6 state=floating
bspc rule -a *:mupen64plus desktop=^6 state=floating
bspc rule -a *:newsboat desktop=^8
bspc rule -a *:mate-calc state=tiled split_ratio=0.35 split_dir=west
bspc rule -a *:mutt desktop=^4
bspc rule -a *:neomutt desktop=^4
bspc rule -a *:ranger desktop=^3
bspc rule -a *:rtorrent desktop=^5
bspc rule -a *:cal state=floating # +external_rules
bspc rule -a *:pinentry state=floating
bspc rule -a *:barrydesktop desktop=^6 state=tiled
bspc rule -a mpv split_ratio=0.7 split_dir=west
bspc rule -a *:play-with-mpv split_ratio=0.7

# ------------------------------------------------------------
# Autostart
# ------------------------------------------------------------

gmailcheck() {
    while true; do
        $DIR_SCRIPTS/gmailcheck.sh
        sleep 5m
    done
}

tvmusor() {
    $DIR_SCRIPTS/tvm -G | gist -u 258bad5f3ca1995fc3d595cf359a36c3 -p -f "TV musor"
}

# always run/restart these programs
xsetroot -cursor_name left_ptr
~/.config/bspwm/panel &
compton -b --config ~/.config/compton/compton.conf
dunst &

# start these programs only once
if [ ! -e /tmp/bspwm_autorun ]; then
    urxvtc &
    urxvtc -name ranger -e ranger &
    #urxvtc -name rtorrent -e rtorrent &
    #urxvtc -name newsbeuter -e newsbeuter &
    geary-light-theme.sh &
    sleep 30s && ~/bin/chromium-privoxy.sh &
    echo "false" > /tmp/bspwm_autorun
    sleep 4m && tvmusor &
fi

gmailcheck &

# vim: set syntax=sh filetype=sh :
