#! /bin/sh

# general settings
bspc config split_ratio             0.50
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config pointer_follows_focus   true

# borders/fill
bspc config borderless_monocle      false
bspc config border_width            2
bspc config focused_border_color    "#0d497b"
bspc config normal_border_color     "#333333"
bspc config presel_feedback_color   "#0d497b"

# gap/padding
gap_size=0
bspc config gapless_monocle         true
bspc config window_gap              $gap_size
bspc config top_padding             $gap_size
bspc config bottom_padding          $gap_size
bspc config left_padding            $gap_size
bspc config right_padding           $gap_size

# tags
bspc monitor -d 1 2 3 4 5 6 7 8 9

# rules
bspc rule -a chromium desktop=^2 focus=on follow=true
