#!/usr/bin/env dash
#                               _
#  ___ _ __   ___ _ __ ___   __| |
# / __| '_ \ / __| '_ ` _ \ / _` |
# \__ | |_) | (__| | | | | | (_| |
# |___| .__/ \___|_| |_| |_|\__,_|
#     |_|
# Created by: spcmd
# http://spcmd.github.io
# https://github.com/spcmd

wid=$1
class=$2
instance=$3

# Move calendar to the top right corner
# TODO: set 'x' and 'y' depending on the screen resolution
if [ "$class" = "cal" ] || [ "$instance" = "cal" ]; then
    xdo move -n cal -x +1175 -y 20
fi

# debug
#echo "$@" >> /tmp/bspwm_rules_debug.log

# vim: set syntax=sh filetype=sh :
